name: cp2k-uenv
version: 2
spack:
  commit: releases/v1.0
  repo: https://github.com/spack/spack.git
  packages:
    repo: https://github.com/spack/spack-packages.git
    commit: 4568e82f27a390c46b0fc710aa68e534ae54277b
store: /user-environment
description: CP2K Beverin uenv
