gcc-env:
  compiler: [gcc]
  network:
      mpi: cray-mpich@8.1.32
      specs: [ 'libfabric@2.3' ]
  unify: true
  specs:
  - q-e-sirius@1.0.2 hdf5=parallel
  - sirius@7.10.0 +nlcglib
  - nlcglib@1.3.0
  variants:
  - +mpi
  views:
    default:
      link: roots
      uenv:
        add_compilers: true
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
