name: gromacs-gh200-pytorch
store: /user-environment
description: GPU-optimised GROMACS with PLUMED and PyTorch, and the toolchain to build your own GROMACS.
spack:
  repo: https://github.com/spack/spack.git
  commit: releases/v1.0
  packages:
    repo: https://github.com/spack/spack-packages.git
    commit: f5e96586306f35c10c473b9fc2f33e561f711373
modules: false
version: 2
