site_name: alps-uenv
nav:
  - Home: index.md
  - 'uenv':
    - 'Overview': uenv-overview.md
    - 'cp2k': uenv-cp2k.md
    - 'editors': uenv-editors.md
    - 'gromacs': uenv-gromacs.md
    - 'lammps': uenv-lammps.md
    - 'linaro-forge': uenv-linaro-forge.md
    - 'namd': uenv-namd.md
    - 'prgenv-gnu': uenv-prgenv-gnu.md
    - 'quantumespresso': uenv-qe.md
    - 'vasp': uenv-vasp.md
  - 'Developers':
    - 'tutorial: application': pkg-application-tutorial.md
  - 'Compilation':
    - 'uenv and Spack': uenv-compilation-spack.md
theme:
  name: material
  features:
    - content.code.copy
    - navigation.tabs
  palette:
    primary: deep orange
    accent: deep orange
markdown_extensions:
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
extra_css:
  - stylesheets/extra.css
repo_url: https://github.com/eth-cscs/alps-uenv
