name: gromacs-gh200
store: /user-environment
description: GPU-optimised GROMACS with and without PLUMED, and the toolchain to build your own GROMACS.
spack:
  repo: https://github.com/spack/spack.git
  commit: develop
modules: false
