nvidia-mp:
  compiler: [gcc]
  network:
    mpi: cray-mpich
    specs:
    - libfabric@2.3.0
  unify: true
  specs:
  - cuda@12.6
  - nccl@2.27
  - nccl-tests
  - aws-ofi-nccl
  - nvshmem +mpi +cuda +nccl +libfabric +gdrcopy ~ucx
  - cublasmp
  - cufftmp
  - cusolvermp
  variants:
  - +mpi
  - +cuda
  - cuda_arch=90a
  views:
    default:
      link: roots
      uenv:
        add_compilers: true
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
