gcc-env:
  compiler: [gcc]
  network:
      mpi: cray-mpich@8.1.32+rocm
  unify: when_possible
  specs:
  - q-e-sirius@1.0.1 hdf5=parallel
  - sirius@7.9 +nlcglib +rocm +magma +apps
  - nlcglib@1.3.0+gpu_direct~openmp
  - spfft+gpu_direct
  - hip@6.3.3 ^mesa@23.3.6
  variants:
  - amdgpu_target=gfx90a
  - amdgpu_target_sram_ecc=gfx90a
  views:
    sirius:
      link: roots
      uenv:
        add_compilers: true
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
