cp2k:
  compiler: [gcc]
  unify: true
  specs:
  - cmake
  - ninja
  - libtool@2.4.6
  - openblas threads=openmp
  - netlib-scalapack
  - fftw
  - libxc
  - spglib
  - spla
  - elpa
  - plumed
  - libvori
  # py-torch
  - py-torch ~distributed +custom-protobuf
  - protobuf
  - py-protobuf
  # libint
  - libint
  - eigen@3
  # pika
  - pika@0.34.0 malloc=mimalloc +stdexec
  - stdexec@25.03.rc1
  - mimalloc
  - boost
  - fmt
  - spdlog
  - hwloc
  - whip
  # Umpire
  - umpire
  - blt
  - camp
  # DLA-Future
  - dla-future@0.10.0 +scalapack +miniapps +hdf5
  - blaspp
  - lapackpp
  - dla-future-fortran@0.5.0
  # DFTD4
  - dftd4
  - multicharge
  - mctc-lib~openmp
  # COSMA
  - costa
  - cosma
  # SIRIUS
  - hdf5
  - spfft
  - sirius@7.9.0 +dlaf +elpa +scalapack
  # CP2K
  - dbcsr
  - cp2k@2025.2 +libxc +libint +spglib +cosma +spla +elpa +dlaf +sirius +plumed +dftd4 +libvori +pytorch lmax=5 build_system=cmake
  variants:
    - +mpi
    - +openmp
    - ~cuda
    - ~rocm
    - build_type=Release
  network:
    mpi: cray-mpich@8.1.32
    specs:
      - libfabric@2.3
  views:
    develop:
      link: roots
      exclude: ["cp2k"]
    cp2k:
      link: roots
