name: q-e-sirius
version: 2
spack:
  commit: releases/v1.1
  repo: https://github.com/spack/spack.git
  packages:
    repo: https://github.com/spack/spack-packages.git
    commit: 5f20b9190596e0b875141e8cee03f0d3847ad65c
store: /user-environment
description: q-e-sirius uenv
