gcc-env:
  compiler: [gcc]
  network:
      mpi: cray-mpich@8.1.32+cuda
      specs: [ 'libfabric@2.3 +cuda' ]
  unify: true
  specs:
  - q-e-sirius@1.0.2 hdf5=parallel
  - sirius@7.10 +nlcglib +cuda
  - nlcglib@1.3.0+gpu_direct
  - spfft+gpu_direct
  - cuda
  variants:
  - cuda_arch=90
  views:
    default:
