gcc-env:
  compiler: [gcc]
  network:
      mpi: cray-mpich@8.1.32
      specs:
      - libfabric@2.3
  unify: true
  specs:
  - boost +chrono +filesystem +iostreams +mpi +program_options +python +regex +serialization +shared +system +timer
  - cmake
  - fftw
  - fmt
  - gmp
  - gsl
  - hdf5+cxx+hl+fortran
  - kokkos +aggressive_vectorization cxxstd=17 +openmp +pic +serial +shared +tuning
  - kokkos-kernels +blas +execspace_openmp +execspace_serial +lapack +openmp scalars=float,double,complex_float,complex_double +serial +shared +superlu
  - kokkos-tools +mpi +papi
  - netlib-scalapack
  - lua
  - libtree
  - lz4
  - meson
  - netcdf-c build_system=cmake
  - netcdf-cxx
  - netcdf-cxx4
  - netcdf-fortran
  - ninja
  - openblas threads=openmp
  - osu-micro-benchmarks
  - python
  - superlu
  - zlib-ng
  variants:
  - +mpi
  views:
    default:
      link: roots
      uenv:
        add_compilers: true
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
