name: ascent
store: /user-tools
description: "Ascent/0.9.5 in-situ visualization library v2"
spack:
  repo: https://github.com/spack/spack.git
  commit: releases/v1.0
  packages:
    repo: https://github.com/spack/spack-packages.git
    commit: releases/v2025.07
modules: true
version: 2
