ascent-env:
  compiler: [gcc]
  network:
    mpi: cray-mpich
  unify: true
  specs:
    - cmake
    - python

    - ascent +python +occa ~adios2 ~mfem ~fides
    - conduit +hdf5

    - hdf5 +cxx+hl

    # because of vtk-m issue
    - cuda@12.8
  views:
    default:
      link: run
      uenv:
        add_compilers: true
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
