gromacs:
  compiler: [gcc]
  network:
    mpi: cray-mpich@8.1.32 +cuda
  unify: when_possible
  specs:
  - cmake
  - cuda@12.9
  - blas
  - lapack
  - hwloc
  - fftw
  - python@3.12
  - gromacs@2025.3 +cuda +mpi +hwloc
  - gromacs@2023.5 +plumed +cuda +hwloc
  mpi:
    spec: cray-mpich
    gpu: cuda
  variants:
  - +mpi
  - +cuda
  - cuda_arch=90a
  views:
    develop:
      exclude: ['gromacs']
    gromacs:
      exclude: ['gromacs+plumed']
      link: run
    plumed:
      exclude: ['gromacs@2025.3']
      link: run
  packages:
  - perl

