name: prgenv-gnu
spack:
  commit: releases/v0.22
  repo: https://github.com/spack/spack.git
store: /user-environment
description: GNU Compiler toolchain with cray-mpich, Python, CMake and other development tools.

