name: gromacs-gh200
store: /user-environment
description: GPU-optimised GROMACS with and without PLUMED, and the toolchain to build your own GROMACS.
spack:
  commit: releases/v1.0
  repo: https://github.com/spack/spack.git
modules: false
