gromacs:
  mpi:
    spec: cray-mpich
    gpu: cuda
  compiler:
  - toolchain: gcc
    spec: gcc@12.3
  unify: when_possible
  specs:
  - cmake
  - cuda@12.4
  - blas
  - lapack
  - hwloc
  - fftw
  - python@3.10
  - gromacs@2024.1 +cuda +mpi +hwloc
  - gromacs@2022.5 +plumed +cuda +hwloc
  variants:
  - +mpi
  - +cuda
  - cuda_arch=90
  views:
    develop:
      exclude: ['gromacs']
    gromacs:
      exclude: ['gromacs+plumed']
      link: run
    plumed:
      exclude: ['gromacs@2024.1']
      link: run
  packages:
  - perl

