prgenv-nvidia:
  compiler:
    - toolchain: gcc
      spec: gcc
    - toolchain: llvm
      spec: nvhpc
  unify: when_possible
  mpi:
    spec: cray-mpich@8.1.26%nvhpc
    gpu: cuda
  packages:
  - perl
  - curl
  - gmake
  - autoconf
  - automake
  specs:
  #- osu-micro-benchmarks@5.9%nvhpc
  - cuda@11.8
  - eccodes@2.25.0%nvhpc +tools +fortran +aec +openmp jp2k=jasper
  - eccodes@2.19.1%nvhpc +tools +fortran +aec +openmp jp2k=jasper
  - netcdf-c@4.8.1%nvhpc
  - netcdf-fortran@4.5.4%nvhpc
  - hdf5@1.12.2%nvhpc +szip +hl +fortran +mpi
  - openblas@0.3.21%nvhpc
  - libfyaml@0.7.12%nvhpc
  variants:
  - cuda_arch=80
  - +mpi
  - +cuda
  views:
    prgenv-icon:
      exclude: ['eccodes@2.19.1']
      link: roots
