arbor:
  compiler:
      - toolchain: gcc
        spec: gcc
  mpi:
      spec: cray-mpich@8.1.29
      gpu: cuda
  unify: true
  specs:
  # arbor
  - arbor@0.9 +python
  # build tools
  - cuda@12.4
  - python@3.11
  - cmake
  - ninja
  # C++ dependencies
  - fmt
  - pugixml
  - nlohmann-json
  - random123
  # python packages
  - py-mpi4py
  - py-numpy
  - py-pip
  - py-pybind11
  # etc
  - osu-micro-benchmarks
  variants:
  - +mpi
  - +cuda
  - cuda_arch=90
  packages:
  - diffutils
  - gettext
  - gmake
  - libxml2
  - perl
  views:
    arbor:
      link: roots
    develop:
      link: roots
      exclude: [arbor]
