name: cp2k
store: /user-environment
spack:
    repo: https://github.com/spack/spack.git
    commit: releases/v1.0
    packages:
        repo: https://github.com/spack/spack-packages.git
        commit: 35c1993d06da97b2d94156ff6053b1ab2eb70914
modules: true
version: 2
