name: ascent
store: /user-tools
description: "Ascent in-situ visualization library"
spack:
  repo: https://github.com/spack/spack.git
  packages:
    repo: https://github.com/spack/spack-packages.git
version: 2
