name: ascent
store: /user-tools
description: "Ascent in-situ visualization library"
spack:
  repo: https://github.com/spack/spack.git
  commit: releases/v1.1
  packages:
    repo: https://github.com/spack/spack-packages.git
    commit: e2a989af46f57456c4a06f1e0a510ca232d86b6b
version: 2
