lammps-kokkos:
  compiler: [gcc]
  network:
    mpi: cray-mpich@8.1.32 +cuda
  unify: true
  specs:
  - python@3.12
  - cmake
  - ninja
  - cuda@12
  - py-torch@2.8.0 ~distributed ~nccl
  - kokkos +wrapper
  - plumed
  - libmetatensor-torch@0.8.1
  - libmetatomic-torch
  - lammps@git.da995e94a6f62b99fa4d2be9342990fe433b7ce4=develop +kokkos fft_kokkos=cufft +python +replica +mc +misc +plumed +manifold +metatomic +qtb +reaction +shock +spin +extra-pair +extra-fix
  variants:
  - +mpi
  - +cuda
  - cuda_arch=90
  views:
    develop:
      link: all
      exclude: ["lammps"]
      uenv:
        add_compilers: true
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
    lammps:
      link: all
      uenv:
        add_compilers: true
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
