name: q-e-sirius
version: 2
spack:
  commit: releases/v1.1
  repo: https://github.com/spack/spack.git
  packages:
    repo: https://github.com/spack/spack-packages.git
    commit: 4568e82f27a390c46b0fc710aa68e534ae54277b
store: /user-environment
description: q-e-sirius uenv
