name: vasp
spack:
  repo: https://github.com/spack/spack.git
  commit: releases/v1.1
  packages:
    repo: https://github.com/spack/spack-packages.git
    commit: v2025.11.0
store: /user-environment
description: VASP
version: 2
