version: 2
name: ParaView
store: /user-environment
spack:
  repo: https://github.com/spack/spack.git
  commit: 88f3dd435f6ef0ca575a629c446142a8befcf54e # last known working version
  packages:
    repo: https://github.com/spack/spack-packages.git
description: ParaView for Alps Zen2 clusters using OSMesa (Off Screen Mesa)
modules: false
