cp2k:
  compiler:
  - toolchain: gcc
    spec: gcc@12.3
  unify: true
  specs:
  - cmake
  - ninja
  - cuda@12.4 # Can't be newer than driver version, for DBCSR
  - openblas threads=openmp
  - netlib-scalapack
  - fftw
  - libxc@7 ~cuda build_system=cmake
  - spglib
  - spla
  - elpa
  - plumed
  # libint
  - libint
  - eigen@3
  # pika
  - pika malloc=mimalloc
  - mimalloc
  - boost
  - fmt
  - spdlog
  - hwloc
  - whip
  # Umpire
  - umpire
  - blt
  - camp
  # DLA-Future
  - dla-future +mpi_gpu_aware +mpi_gpu_force_contiguous +scalapack +miniapps
  - blaspp
  - lapackpp
  - dla-future-fortran
  # DFTD4
  - dftd4
  - multicharge
  - mctc-lib
  # COSMA
  - tiled-mm
  - costa
  - cosma +gpu_direct
  # SIRIUS
  - hdf5
  - spfft
  - sirius +dlaf +elpa +scalapack
  # CP2K
  - dbcsr@2.8.0
  - cp2k@2025.1 +libxc +libint +spglib +cosma +spla +elpa +dlaf +sirius +plumed +dftd4 lmax=5 build_system=cmake
  variants:
    - +mpi
    - +openmp
    - +cuda
    - cuda_arch=90
    - build_type=Release
  mpi:
    spec: cray-mpich@8.1.30
    gpu: cuda
  views:
    develop:
      link: roots
      exclude: ["cp2k"]
    cp2k:
      link: roots
