name: pytorch
spack:
  repo: https://github.com/spack/spack.git
  #commit: develop
  commit: 9ea9bc1d6b92cc3c3de14c713c37d6adf5126163
  packages:
    repo: https://github.com/spack/spack-packages.git
    commit: 012d4b2c63b801a5287d994b29d5caf0096a68f8
    #repo: https://github.com/boeschf/spack-packages.git
    #commit: my-develop
modules: false
store: /user-environment
description: pytorch and friends
version: 2
