gcc-env:
  compiler:
      - toolchain: gcc
        spec: gcc@11
  mpi:
      spec: cray-mpich
      gpu: cuda
  unify: true
  specs:
  - cmake
  - fftw
  - fmt
  - hdf5
  - ninja@1.11
  - openblas threads=openmp
  - python@3.11
  - py-pybind11
  - osu-micro-benchmarks@5.9
  - cuda@11.8
  variants:
  - +mpi
  - +cuda
  - cuda_arch=80
  views:
    default:
